spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krishnamurthypradeep/ConfigData1
---
spring:
  application:
    name: springcloudconfigserver
    
server:
  port: 8888    